# Generated by Django 5.2 on 2025-04-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='participant',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
