# Generated by Django 5.2 on 2025-04-26 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_participants_alter_submission_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='Event_date',
        ),
        migrations.AddField(
            model_name='event',
            name='Event_Start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='Event_end_Date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='Registration_last_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Submissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
